#!/usr/bin/env bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -eo pipefail

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
else
  hash swiftlint 2>/dev/null  || {
    echo "==> Installing swiftlint…"
    brew install swiftlint
  }
  hash xcodegen 2>/dev/null  || {
    echo "==> Installing xcodegen…"
    brew install xcodegen
  }
fi

# if [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
#   echo "==> Installing Ruby…"
#   rbenv install --skip-existing
#   which bundle >/dev/null 2>&1  || {
#     gem install bundler
#     rbenv rehash
#   }
# fi

if [ -f "Gemfile" ]; then
  hash bundle 2>/dev/null || {
    echo "==> Installing gem bundler 2.1.4…"
    gem install bundler -v 2.1.4 --no-document --quiet
  }
  echo "==> Installing gem dependencies…"
  bundle config set path 'vendor/gems'
  bundle check >/dev/null 2>&1  || {
    bundle install --quiet
  }
fi
