#!/bin/bash

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -ev

cd "$(dirname "$0")/.."

echo "CI started at…"
date "+%H:%M:%S"

# check FASTLANE_LANE parameter
if [ -n "$1" ]; then
  # pass arguments to cibuild call. This is useful for calling a single lane.
  export FASTLANE_LANE="$1"
else
  echo >&2 "Please provide an Environment parameter (e.g. ci_build, code_coverage)"
  exit 1
fi


# check FASTLANE_ENV parameter
if [ -n "$2" ]; then
  # pass arguments to test call. This is useful for calling a single test.
  export FASTLANE_ENV="$2"
else
  echo >&2 "Please provide an Environment parameter (e.g. default, ios12_xcode10, osx)"
  exit 1
fi

# run tests
echo "Running tests…"
date "+%H:%M:%S"

# run cibuild.
bundle exec fastlane $FASTLANE_LANE configuration:Debug --env $FASTLANE_ENV
bundle exec fastlane $FASTLANE_LANE configuration:Release --env $FASTLANE_ENV
