#!/bin/bash

# script/lint: Run lint for application.

set -ev

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

script/update

echo "==> Running static analysis…"

bundle exec fastlane static_code_analysis
