#!/bin/bash

# script/server: Launch the application and any extra required processes
#                locally.

set -ev

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update

echo "Server is not applicable for this project"
