#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -ev

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Setting up xcodeproj…"
bundle exec fastlane generate_xcodeproj

echo "==> Project is now ready to go!"
