#!/bin/bash

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.


set -ev

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

script/update

echo "==> Running tests…"

bundle exec fastlane test_framework

echo "==> Running static analysis…"

bundle exec fastlane static_code_analysis
