name: Xcode - Build and Analyze

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.3'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: make setup
      - name: Danger
        run: |
          bundle exec danger
          bash <(curl -s https://codecov.io/bash) -J 'DataKit'
      - name: Test code Coverage
        run: make cibuild FL_LANE=code_coverage FASTLANE_ENV=default
      - name: Build iOS
        run: make cibuild FASTLANE_ENV=ios13_xcode11
      - name: Build macOS
        run: make cibuild FASTLANE_ENV=osx15
